import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";

const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
});
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
